[package]
name = "fast-mem"
version = "0.1.0"
edition = "2024"

[profile.release]
debug = true
lto = "fat"
panic = "abort"
strip = false
opt-level = 3

[dependencies]
libc = "0.2.180"
memmap2 = "0.9.9"
